instance_id: provider-192.168.1.4
log_level: info
request_timeout: 30s
nats_address: nats://localhost:4222
nats_task_subscription_subject_pattern: tasks.dispatch.%s.*
nats_job_status_update_subject_prefix: jobs.status
nats_command_timeout: 10s
provider_registry_service_name: provider-registry
provider_heartbeat_interval: 30s
workspace_dir: /var/folders/8h/0d_tyzp576xf4h0j62__5pwr0000gn/T/dante_tasks
