port: ":8002"
log_level: "info"
request_timeout: 30s # Default request timeout for HTTP server

# Database Configuration
database_url: "postgresql://dante_user:dante_password@postgres:5432/dante_registry?sslmode=disable" # Updated for Docker and credentials

# Consul Configuration
consul_address: "consul:8500" # Updated for Docker
service_name: "provider-registry"
service_id_prefix: "provider-reg-"
service_tags:
  - "dante"
  - "registry"
health_check_path: "/health"
health_check_interval: 10s
health_check_timeout: 2s 