# Basic configuration for the Provider Daemon
instance_id: "provider-daemon-01" # Unique ID for this daemon instance (should be configurable, e.g. hostname or a UUID)
log_level: "info"                 # debug, info, warn, error
request_timeout: "30s"            # General request timeout (e.g. for Provider Registry API calls)

# NATS Configuration
nats_address: "nats://localhost:4222"
# Subject pattern the daemon will subscribe to for tasks. %s will be replaced by instance_id.
nats_task_subscription_subject_pattern: "tasks.dispatch.%s.*"
# Prefix for subjects where daemon publishes job status updates. E.g., jobs.status.{job_id}
nats_job_status_update_subject_prefix: "jobs.status"
nats_command_timeout: "10s" # Timeout for NATS operations like publish, request

# Provider Registry Configuration (for heartbeats)
provider_registry_service_name: "provider-registry" # Name of the provider registry service in Consul
# Alternatively, a direct URL:
# provider_registry_url: "http://localhost:8002"
provider_heartbeat_interval: "30s"

# Task Execution Configuration (Placeholders)
# workspace_dir: "/tmp/dante_tasks" # Base directory for task files
# docker_endpoint: "unix:///var/run/docker.sock" # For Docker-based execution

# GPU Configuration (Placeholders)
# managed_gpu_ids: ["0", "1"] # Specific GPU UUIDs or indices this daemon manages 